# Generated by Django 3.0.2 on 2020-01-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_location', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='ChurchDetails',
        ),
    ]
