# Generated by Django 3.0.2 on 2020-01-17 08:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_location', '0002_auto_20200116_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchdetails',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4128),
        ),
    ]
